import { WorkspaceState } from '@/types/workspace.types';

/** Sample layout for a sticker & sign shop. */
export const defaultWorkspace: WorkspaceState = {
  title: 'PrintOps — Sticker & Sign Shop',
  gridColumns: 12,
  theme: {
    mode: 'dark',
    accent: '#3b82f6',
    radius: 10,
    density: 'normal',
  },
  navigation: [{ id: 'dashboard', label: 'Dashboard', path: '/workspace' }],
  panels: [
    {
      id: 'print-queue',
      name: 'Print Queue',
      widget: 'production',
      col: 1,
      colSpan: 8,
      row: 1,
      rowSpan: 2,
      style: { accentBar: '#3b82f6' },
    },
    {
      id: 'revenue',
      name: 'Revenue',
      widget: 'revenue',
      col: 9,
      colSpan: 4,
      row: 1,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'machine-status',
      name: 'Equipment',
      widget: 'machineStatus',
      col: 9,
      colSpan: 4,
      row: 2,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'active-orders',
      name: 'Active Orders',
      widget: 'activeOrders',
      col: 1,
      colSpan: 5,
      row: 3,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'proof-approvals',
      name: 'Proof Approvals',
      widget: 'proofApprovals',
      col: 6,
      colSpan: 4,
      row: 3,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'material-stock',
      name: 'Vinyl Stock',
      widget: 'materialStock',
      col: 10,
      colSpan: 3,
      row: 3,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'design-gallery',
      name: 'Recent Designs',
      widget: 'designGallery',
      col: 1,
      colSpan: 7,
      row: 4,
      rowSpan: 1,
      style: {},
    },
    {
      id: 'pending-quotes',
      name: 'Pending Quotes',
      widget: 'pendingQuotes',
      col: 8,
      colSpan: 5,
      row: 4,
      rowSpan: 1,
      style: {},
    },
  ],
};
